application: telehex3001
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/email_update
  script: main.application
  login: admin
- url: /static
  static_dir: static
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: 2.3
- name: django
  version: 1.4
- name: PIL
  version: 1.1.7

env_variables:
  DJANGO_SETTINGS_MODULE: 'telehex_django.settings'
