application: telehex3001
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
script: telehex.application

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: 2.3
